runSortData:
	./SortData.py --inputPath '/home/shell/Data/DS/' --dsName 'transactions' --dsNameExtension 'withKey.jsonl'

runInvestigateAndTagDuplicates:
	./InvestigateAndTagDuplicates.py --inputPath '/home/shell/Data/DS/' --dsName 'transactions' --dsNameExtension 'Sorted.withKey.jsonl'

