runSortData:
	./SortData.py --inputPath '/home/shell/Data/DS/' --dsName 'transactions' --dsNameExtension '.withKey.txt'

runInvestigateAndTagDuplicates:
	./InvestigateAndTagDuplicates.py --inputPath '/home/shell/Data/DS/' --dsName 'transactions' --dsNameExtension '.sorted.withKey.txt'

