runSummaryStats:
	./GenerateSummaryStats.py --inputPath '/home/shell/Data/DS/' --dsName 'transactions' --dsNameExtension '.txt'

runFrequenciesHistograms:
	./GenerateFrequenciesHistograms.py --inputPath '/home/shell/Data/DS/' --dsName 'transactions' --dsNameExtension '.txt'

runAddKeyIndsAndDropFields:
	./AddKeyIndsAndDropFields.py --inputPath '/home/shell/Data/DS/' --dsName 'transactions' --dsNameExtension '.txt'