runConvertCsvToJsonl:
	./ConvertCsvToJsonl.py --inputPath '/home/shell/Data/DS/' --dsName 'transactions' --dsNameExtension 'csv'

runSummaryStats_csv:
	./GenerateSummaryStats.py --inputPath '/home/shell/Data/DS/' --dsName 'transactions' --dsNameExtension 'csv'

runSummaryStats_jsonl:
	./GenerateSummaryStats.py --inputPath '/home/shell/Data/DS/' --dsName 'transactions' --dsNameExtension 'jsonl'

runFrequenciesHistograms:
	./GenerateFrequenciesHistograms.py --inputPath '/home/shell/Data/DS/' --dsName 'transactions' --dsNameExtension 'jsonl'

runAddKeyIndsAndDropFields:
	./AddKeyIndsAndDropFields.py --inputPath '/home/shell/Data/DS/' --dsName 'transactions' --dsNameExtension 'jsonl'